sudo: required
dist: trusty
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y cabal-install
    - cabal update
    - git clone https://github.com/koalaman/shellcheck.git
    - cd shellcheck
    - cabal install
    - cd ..
    - export PATH="$HOME/.cabal/bin:$PATH"
    - which shellcheck
script:
    make lint
